---
title: Trabajando en el SML
title-en: Working at the Morgue
description: Taller de narrativa policial
description-en: Crime fiction writing workshop
date: "2020-10-24"
categories: [escritura, cuento]
categories-en: [writing, story]
---

::: {.content-visible when-profile="esp"}
La puerta del vagón de metro se abre puntualmente a las 9:37 pm en la estación Puerto. Sergio espera tranquilamente, y sube en los últimos segundos, como si diera lo mismo quedarse o ir a algún sitio. No recuerda haber tenido un día tan difícil como el de hoy, y todavía le falta al menos una hora para llegar a casa. No es necesario esperar mucho tiempo para que comience la venta informal de alfajores y cuchuflís caseros, sánguches de jamón-queso o hamburguesas veganas. Sergio sabe que tendrán que pasar algunas horas y al menos un vaso de alcohol antes de que su estómago se recupere. Hoy ha sido un día particularmente intenso en el Servicio de Medicina Legal de Valparaíso. Comenzó su turno de 12 horas a las 8 am con los borrachos del puerto. Normalmente esos casos llegan durante la noche y se analizan antes de su turno. Esta vez y como ha sido la tónica de los últimos meses, el trabajo se acumula y desborda al turno que sigue. Pero no ha sido eso lo que le ha revuelto el estómago. Ya se ha acostumbrado al hedor a alcohol, orina y mierda, a sus cuerpos desangrados tras peleas callejeras o bañados en vómito en un último reflejo del cuerpo antes de rendirse a la intoxicación. Tampoco lo afectaron los otros cuerpos destrozados que llegaron durante el día: el abuelo, el atropellado, quemados y un largo etcétera. El día no había sido distinto de cualquier otro en la morgue hasta el cuerpo de esa adolescente de 12 años que llegó a las cuatro de la tarde. La morgue. Nunca le gustó ese nombre. Como francés. Como el tatuaje que tenía esa chica muerta cuya imagen sobre la tabla de autopsia todavía le perturbaba: Aujourd’hui. ¿Porqué una palabra tan larga cuando un simple “hoy” hubiera bastado, y sobre todo porqué el tatuaje era evidentemente tan reciente?

Trata de no pensar y no recordar. Mira la gente que subía y bajaba del vagón. Envidia su despreocupación y alegría. Desde que había comenzado su trabajo como asistente de médico de autopsia, se sentía cada vez más solitario y apartado. Aunque antes de salir del SML ya se había dado un baño completo y refregado con jabón después de su turno, y está usando ropa completamente distinta, siente todavía el olor a muerte pegado a sus fosas nasales. Sergio busca indicios de que ese olor no está solo en su cabeza. Examina los gestos de los pasajeros que rehúyen el contacto visual, no por lo que huelen, sino por esa mirada vacía y tenebrosa que los intimida. Trata de no seguir pensando en aquello, pero la fragilidad del cuerpo humano le es aterradora: el cuerpo, a pesar de su exterior pulcro y limpio, no es más que una piñata de sangre, músculos y vísceras en un equilibrio químico primario. Cuántas veces no le había tocado abrir un cadáver producto de un accidente para descubrir un cáncer que también lo hubiera matado en menos de un año. Sin embargo, las personas siguen su día a día sin la preocupación de las innumerables maneras que tienen de morir. Miraba sus caras, pensando que con seguridad alguno de ellos estaría en el frío mesón metálico de la autopsia antes de que terminara el año. Se preguntaba si ese cinismo y frialdad desaparecería en algún momento, o si ya había tomado un camino en el cual ya no había vuelta atrás. La ignorancia es felicidad, pensaba, y cuanto daría por olvidar esas imágenes que volvían sin remedio a su cabeza.
:::

::: {.content-visible when-profile="eng"}
The subway car door opens punctually at 9:37 pm at Puerto station. Sergio waits calmly, and boards in the final seconds, as if it made no difference to stay or go somewhere. He doesn't recall ever having a day as hard as today, and he still has at least an hour to go before reaching home. There's no need to wait long before the informal selling begins: homemade alfajores and cuchuflís, ham-and-cheese sandwiches or vegan burgers. Sergio knows several hours and at least one glass of alcohol will have to pass before his stomach recovers. Today has been a particularly intense day at the Legal Medicine Service of Valparaíso. He started his 12-hour shift at 8 am with the port's drunks. Normally those cases come in during the night and are examined before his shift. This time, as has been the norm over the last few months, the work piles up and overflows onto the shift that follows. But that isn't what turned his stomach. He's already grown used to the stench of alcohol, urine and shit, to the bodies drained of blood after street fights or bathed in vomit in a last reflex of the body before surrendering to intoxication. Nor was he affected by the other broken bodies that came in during the day: the old man, the run-over victim, the burned ones and a long etcetera. The day had been no different from any other at the morgue until the body of that 12-year-old girl who arrived at four in the afternoon. The morgue. He never liked that name. So French. Like the tattoo that dead girl had, whose image on the autopsy table still disturbed him: Aujourd’hui. Why such a long word when a simple "today" would have sufficed, and above all, why was the tattoo so evidently recent?

He tries not to think and not to remember. He watches the people getting on and off the car. He envies their carefreeness and joy. Since he had started his job as an autopsy doctor's assistant, he felt more and more solitary and set apart. Even though before leaving the morgue he had already taken a full shower and scrubbed himself with soap after his shift, and he is wearing completely different clothes, he still feels the smell of death clinging to his nostrils. Sergio looks for signs that the smell isn't only in his head. He examines the gestures of the passengers who avoid eye contact, not because of what they smell, but because of that empty, sinister gaze that intimidates them. He tries not to keep thinking about it, but the fragility of the human body terrifies him: the body, despite its tidy, clean exterior, is nothing but a piñata of blood, muscles and viscera in a primitive chemical balance. How many times had he had to open a corpse from an accident only to discover a cancer that would also have killed it in less than a year. And yet, people go about their day to day without worrying about the countless ways they have of dying. He looked at their faces, thinking that surely one of them would be on the cold metal autopsy table before the year was out. He wondered whether that cynicism and coldness would disappear at some point, or whether he had already taken a path from which there was no turning back. Ignorance is bliss, he thought, and how much he would give to forget those images that kept coming back, helplessly, into his head.
:::
