project:
  type: website

website:
  title: "sebastiandres.xyz"
  favicon: favicon.ico
  google-analytics: "G-HG9BYLK8FC"
  site-url: "https://sebastiandres.xyz"
  navbar:
    right:
      - index.qmd
      - pages/blog.qmd
      - pages/historias.qmd
      - pages/charlas.qmd
      - pages/proyectos.qmd
      - pages/librerias.qmd
      - pages/publicaciones.qmd
      - text: Tutoriales
        menu:
          - tutorial/quarto.qmd
      - pages/about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/sebastiandres/
      - icon: github
        href: https://github.com/sebastiandres
      - icon: twitter
        href: https://twitter.com/sebastiandres
format:
  html:
    theme: superhero
    css: styles.css



