project:
  type: website

website:
  title: "sebastiandres.xyz"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - pages/about.qmd
      - pages/charlas.qmd
      - pages/proyectos.qmd
      - pages/librerias.qmd
      - pages/publicaciones.qmd
      - pages/blog.qmd
  navbar:
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/sebastiandres/
      - icon: github
        href: https://github.com/sebastiandres
      - icon: twitter
        href: https://twitter.com/sebastiandres
format:
  html:
    theme: zephyr
    css: styles.css



