project:
  output-dir: ./_site/    
  render:
    - "*.qmd"
    - "*/*.qmd"
    - "!README.md"
    - "!pages/listing-bilingual.ejs.md"

website:
  title: "sebastiandres"
  favicon: favicon.ico
  google-analytics: "G-HG9BYLK8FC"
  site-url: "https://sebastiandres.xyz"
  navbar:
    left:
      - text: "Blog"
        href: pages/blog.qmd
      - text: "Charlas"
        href: pages/talks.qmd
      - text: "Lecturas"
        href: pages/reading.qmd
      - text: "Proyectos"
        href: pages/projects.qmd
      - text: "Artículos"
        href: pages/articles.qmd
      - text: Tutoriales
        menu:
          - tutorial/quarto.qmd
          - tutorial/streamlit.qmd
          - tutorial/storytelling_by_sanderson.qmd
      - text: "Cuentos"
        href: pages/writing.qmd
    right:
      - text: "Sobre mí"
        href: pages/about.qmd
      - href: ./eng/index.html
        text: ENG
      - icon: rss
        href: pages/blog.xml  # Note: This matches the 'blog.qmd' file name

lang: es

format:
  html:
    theme:
      - default
      - theme-mondrian.scss
    css: styles.css



