project:
  output-dir: ./_site/eng
  render:
    - "*.qmd"
    - "*/*.qmd"
    - "!README.md"
    - "!pages/listing-bilingual.ejs.md"

website:
  title: "sebastiandres"
  favicon: favicon.ico
  google-analytics: "G-HG9BYLK8FC"
  site-url: "https://sebastiandres.xyz/eng"
  navbar:
    left:
      - text: "Blog"
        href: pages/blog.qmd
      - text: "Talks"
        href: pages/talks.qmd
      - text: "Reading"
        href: pages/reading.qmd
      - text: "Projects"
        href: pages/projects.qmd
      - text: "Articles"
        href: pages/articles.qmd
      - text: Tutorials
        menu:
          - tutorial/quarto.qmd
          - tutorial/streamlit.qmd
          - tutorial/storytelling_by_sanderson.qmd
      - text: "Stories"
        href: pages/writing.qmd
    right:
      - text: "About me"
        href: pages/about.qmd
      - href: ../index.html
        text: ESP
      - icon: rss
        href: pages/blog.xml  # Note: This matches the 'blog.qmd' file name

lang: en

format:
  html:
    theme:
      - default
      - theme-mondrian.scss
    css: styles.css



