---
title: "Streamlit: apps y posts"
title-en: "Streamlit: apps and posts"
description: "Novedades y creaciones recientes"
description-en: "Recent news and creations"
date: "2022-01-21"
categories: [streamlit]
---

::: {.content-visible when-profile="esp"}
El 2021 fui prolífico en la creación de apps de Streamlit, y este año tiene pinta de que será similar. Recién salido del horno, he publicado en el blog de Streamlit un post sobre la utilización de la librería streamlit_book: [How to create interacrtive books with streamlit and streamlit_book in 5 steps](https://blog.streamlit.io/how-to-create-interactive-books-with-streamlit-and-streamlit-book-in-5-steps/).
Esencialmente, ilustra el paso a paso de la construcción de la app de [Happy Birds](https://share.streamlit.io/sebastiandres/streamlit_happy_birds/main/happy_birds.py).

También recientemente lancé un app en Streamlit sobre la [matriz de confusión](https://share.streamlit.io/sebastiandres/ml-edu-1-confusion-matrix/main) con el efecto matrix y otras cosas graciosas.

Otras apps de Streamlit:
* [PPT 2 RISE](https://share.streamlit.io/sebastiandres/streamlit_ppt2rise/main): Para convertir presentaciones de powerpoint a jupyter notebook con RISE.
* [xkcd plots](https://share.streamlit.io/sebastiandres/streamlit_xkcd/main): Para graficar funciones en línea tipo xkcd.
* [Webapps con Streamlit](https://share.streamlit.io/sebastiandres/talk_2021_11_pyconcl/main): la presentación de la PyconCL 2021, hecha completamente en Streamlit.
:::

::: {.content-visible when-profile="eng"}
In 2021 I was prolific in creating Streamlit apps, and this year looks like it will be similar. Fresh out of the oven, I have published on the Streamlit blog a post about using the streamlit_book library: [How to create interacrtive books with streamlit and streamlit_book in 5 steps](https://blog.streamlit.io/how-to-create-interactive-books-with-streamlit-and-streamlit-book-in-5-steps/).
Essentially, it illustrates the step-by-step construction of the [Happy Birds](https://share.streamlit.io/sebastiandres/streamlit_happy_birds/main/happy_birds.py) app.

I also recently launched a Streamlit app about the [confusion matrix](https://share.streamlit.io/sebastiandres/ml-edu-1-confusion-matrix/main) with the matrix effect and other funny things.

Other Streamlit apps:
* [PPT 2 RISE](https://share.streamlit.io/sebastiandres/streamlit_ppt2rise/main): To convert powerpoint presentations to jupyter notebook with RISE.
* [xkcd plots](https://share.streamlit.io/sebastiandres/streamlit_xkcd/main): To plot xkcd-style functions online.
* [Webapps con Streamlit](https://share.streamlit.io/sebastiandres/talk_2021_11_pyconcl/main): the PyconCL 2021 presentation, made entirely in Streamlit.
:::
