---
title: The gifts of imperfection
description: "Regalos de la imperfección son el coraje, la compasión y la conexión"
description-en: "The gifts of imperfection are courage, compassion, and connection"
date: "2020-01-10"
author: Brené Brown
genre:  No Ficción
rating: 9
categories: [lectura]
categories-en: [reading]
---

::: {.content-visible when-profile="esp"}
En línea con el libro de “Trillion Dollar Coach”, habla sobre cómo la vulnerabilidad nos conecta como humanos. Los 3 regalos de la imperfección son el coraje, la compasión y la conexión, en una invitación a vivir de manera más auténtica: aceptarnos con nuestras imperfecciones, abrazar nuestros gustos y excentricidades, y dejar de aparentar y creernos el cuento de la madurez. Dos historias me marcaron. La primera: lo importante de no disminuir la importancia de eventos o cosas que sí nos importan para proteger nuestro ego en caso que no resulten, porque tiene como consecuencia que estos mismos eventos no nos alegren o emocionen tanto cuando pasan. La segunda: ser valiente no tiene una única cara. Para una persona extrovertida y osada, ser valiente puede ser no responder un insulto y empezar una pelea. Para una persona introvertida, ser valiente puede ser exactamente lo contrario: responder un insulto y defender su opinión.
:::

::: {.content-visible when-profile="eng"}
In line with the book “Trillion Dollar Coach”, it talks about how vulnerability connects us as humans. The 3 gifts of imperfection are courage, compassion, and connection, in an invitation to live more authentically: to accept ourselves with our imperfections, to embrace our tastes and eccentricities, and to stop pretending and buying into the story of maturity. Two stories stuck with me. The first: how important it is not to downplay the importance of events or things that do matter to us in order to protect our ego in case they don't work out, because the consequence is that these same events don't bring us as much joy or excitement when they happen. The second: being brave doesn't have a single face. For an extroverted, bold person, being brave might mean not responding to an insult and starting a fight. For an introverted person, being brave might be exactly the opposite: responding to an insult and defending their opinion.
:::
