---
title: "Useful not true"
author: "sebastiandres"
date: "2024-09-22"
categories: [libro]
---

::: {.panel-tabset}

## Español

En el libro "Useful not true" Derek nos invita a notar que hay poquísimas cosas que sean 100% reales. El pasado no es real - nuestros recuerdos de él son imprecisos y reescritos a conveniencia. Nuestros pensamientos no son reales - los inventamos para justificar lo que sentimos o ya hemos decidido o hecho. Todo lo creado por el hombre es arbitrario (gobierno, negocios, familia, amigos, pareja, y un largo etcétera). Pero -y aquí reside la belleza simple de esta filosofía de vida- podemos elegir lo que es útil a pesar que no sea verdadero. Notar que estas reglas y convenciones son arbitrarias, nos da el poder de evitarlas, alterarlas o modificarlas.

Estas reglas y convenciones son como un disfraz que vestimos para ser aceptados y que no nos miren raro - pero en realidad nadie nos está mirando. Es como el cuento del "Traje del emperador" pero completamente a la inversa - nadie está realmente atento y preocupado por el disfraz que llevas. Si toda ropa es arbiraria y un disfraz, ¿qué más da probarse otro disfraz, estrafralario y colorido, si sirve mejor a algún otro propósito?

Somos prisioneros de las costumbres y de las historias que nos contamos a nosotros mismos. Por ejemplo, yo pensaba que no podía resolver el [cubo de rubik](https://sebastiandres.xyz/posts/2021/2021-10-29-post-rubik.html) porque lo había intentado algunas veces sin lograrlo - así que ni siquiera me molesté en averiguar que necesitaba para resolverlo. Me cerré en una falsa certeza, hasta que por casualidad alguien reventó esa burbuja con un *"es una habilidad mecánica, cualquiera puede aprenderlo"*. Y en efecto, pronto lo había aprendido. Pero me había negado esa posibilidad por una regla inventada por mí para mí mismo. 

Dudar de tus certezas, de esas reglas que te rodean, te permite repensar lo que quieres y puedes lograr.

> El mundo es tan negociable como un mercado de baratijas en Marrakech. Solo un tonto no regatearía.

> Cada afirmación podría ser precedida por una adventencia: "Desde mi punto de vista limitado, basado solo en lo que he experimentado..."

> Puedes hacer cualquier cosa. Pero no puedes hacer todo. Tienes que decidir. Si no decides, no obtienes nada.

> La teoría más precisa no siempre es la más útil. Y una regla general puede estar lejos de ser verdadera, pero lo suficientemente buena como para llevarte a donde necesitas ir.

> Las creencias existen para guiar tus acciones. Si no estás actuando en línea con tus creencias, no has entendido el sentido de tener una creencia.

> Cuando alguien se niega a usar una herramienta porque no es perfecta, probablemente no esté haciendo realmente el trabajo.

> Eventualmente, no necesitas más información o más tiempo. Ya tienes algunas buenas opciones. Necesitas decidir. Necesitas cambiar de explorador a líder, y guiarte a ti mismo hacia tu objetivo.

## English

In the book "Useful not true" Derek invites us to notice that there are very few things that are 100% real. The past is not real - our memories of it are imprecise and rewritten for convenience. Our thoughts are not real - we invent them to justify what we are feeling or have already decided or done. Everything created by man is arbitrary (government, business, family, friends, partner, and a long etcetera). But -and here lies the simple beauty of this philosophy- we can choose what is useful even if it is not true. Noticing that these rules and conventions are arbitrary gives us the power to avoid, alter, or modify them.

These rules and conventions are like a costume we wear to be accepted in fear of looking odd - but in reality, no one is looking at us. It’s like the story of "The Emperor's New Clothes" but completely the opposite - no one is really paying attention and worried about the disguise you wear. And if all clothing is arbitrary and a disguise, what does it matter to try on another costume, flamboyant and colorful, if it serves a better purpose?

We are prisoners of customs and the stories we tell ourselves. For example, I thought I couldn’t solve the [Rubik's cube](https://sebastiandres.xyz/posts/2021/2021-10-29-post-rubik.html) because I had tried a few times without success - so I didn’t even bother to find out what I needed to solve it. I closed myself off in a false certainty until by chance someone burst that bubble with a *"it's a mechanical skill, anyone can learn it."* And indeed, once I knew I could, I learned how. I couldn't before, as I had denied myself that possibility due to a rule I invented for myself. 

Doubting your certainties and the rules that surround you, allows you to rethink what you want and can achieve. 

> The world is as negotiable as a flea market in Marrakesh. Only a fool doesn’t haggle.

> Every statement everyone says could be prefaced with a disclaimer: “From my limited point of view, based only on what I’ve experienced…”

> You can do anything. But you can’t do everything. You have to decide. If you don’t decide, you get nothing.

> The most accurate theory is not always the most useful. And a rule of thumb can be far from true, but good enough to get you where you need to go.

> Beliefs exist to guide your actions. If you’re not acting in alignment with your beliefs, you’ve missed the point of beliefs.

> When someone refuses to use a tool because it’s not perfect, they’re probably not actually doing the work.

> Eventually, you don’t need more information or time. You’ve found some good options. You need to decide. You need to switch from explorer to leader— to leading yourself.

:::
