---
title: "Metas 2022"
title-en: "Goals 2022"
description: "¿Qué quiero para el 2022?"
description-en: "What do I want for 2022?"
date: "2022-01-21"
categories: [balance, reflexión]
categories-en: [review, reflection]
---

::: {.content-visible when-profile="esp"}
## ¿Qué quiero para el 2022?
Un consejo que he leído en varios lugares es: no proponerse metas puntuales, sino que implementar procesos que permitan alcanzar esas metas. Mi objetivo para este año es crear esos procesos en distintas áreas, con el objetivo de ser feliz. Nada más. Las metas están para movilizar en la dirección correcta, no para decidir que tan exitoso es el año.

### Escritura
Me gustaría:
* Escribir un libro de ficcion
* Escribir un libro de no ficción
* Participar en algunos concursos de escritura, particularmente el de Santiago en 100 palabras (nuevamente)
* Volver a participar en un taller de escritura, como el taller de escritura de novela policial

### Aprendizaje y Creatividad
Creo que tengo una deuda con mis habilidades artísticas: musica y dibujo. Son 2 dimensiones que podría explorar un poco más. Adicionalmente, aprender a tener mejor sentido del humor y reirme más de mi mismo y mis errores.

### Deporte
Como meta quiero hacer al menos 5 minutos de ejercicio al día, de lunes a viernes, durante todo el año. He descubierto que me es más fácil cumplir la meta de ejercicio por las noches, y que puedo aprovechar los 7 minutos de espera de la cafetera francesa para hacer flexiones de brazo. Creo que adicionalmente a eso, necesito salir a correr si quiero poder terminar una maratón.

### Tecnología
Quiero seguir participando en el espacio Open Source. Creo que acá no necesito imponerme mucha disciplina, son cosas que de manera natural van emergiendo:
* Aumentar mi presencia en twitter. Meta: 1000 seguidores.
* Crear nuevas apps en Streamlit: completar la saga de Machine Learning y Matrices de confusión, y hacer el datasaurio.
* Participar en una comunidad de desarrollo de software libre, que puede ser la de RISE.
* Asistir a las PyCons latinoamericanas, particularmente las que está organizando Ariel en Salta. Quizás a alguna otra internacional.

### Lectura
Tengo la meta de leer 10 libros de no-ficción y otros 10 libros de no ficción en el año 2022. Para esto tendré como meta dedicar un poco de tiempo todos los días y leer 1 libro de ficción y otro de no ficción al mes. Hay 2 meses de tolerancia para eventos desafortundados.

En los libros de ficción, seleccioné los que Derek Sivers ha marcado 10/10: https://sive.rs/book

Tema: El mundo
1.- Open Borders - por Bryan Caplan

Tema: Escritura
2.- On Writing Well - por William Zinsser

Tema: la mente
3.- Mindwise: How We Understand What Others Think, Believe, Feel, and Want - por Nicholas Epley
4.- The Time Paradox - por Philip Zimbardo y John Boyd

Tema: Aprendizaje
5.- The Listening Book - por W.A. Mathieu
6.- How Buildings Learn - por Stewart Brand
7.- E-Myth Revisited - por Michael Gerber

Tema: Vida y muerte
8.- Forty Tales from the Afterlives - por David Eagleman
9.- The War of Art - por Steven Pressfield
10.- A Guide to the Good Life: The Ancient Art of Stoic Joy - por William Irvine

Otros libros:
1. Non designer design book
1. Resonate 
1. Creativity INC
1. Invent and Wanter, Jeff Bezos
1. Zero to one
1. So good they cant ignore you
1. Numbers dont lie
1. Think Again
1. Antifragile
1. Almanak of Naval Ravikant
1. Why We Sleep: Unlocking the Power of Sleep and Dreams
1. The Sovereign Individual

En los libros de ficción que me gustaría leer o releer están:
1. Siddhartha, de Herman Hesse.
:::

::: {.content-visible when-profile="eng"}
## What do I want for 2022?
A piece of advice I've read in several places is: don't set specific goals, but instead implement processes that allow you to reach those goals. My objective for this year is to create those processes in different areas, with the goal of being happy. Nothing more. Goals are there to move you in the right direction, not to decide how successful the year is.

### Writing
I would like to:
* Write a fiction book
* Write a non-fiction book
* Take part in some writing contests, particularly Santiago en 100 palabras (again)
* Take part again in a writing workshop, such as the crime novel writing workshop

### Learning and Creativity
I think I have a debt with my artistic skills: music and drawing. They are 2 dimensions I could explore a bit more. Additionally, learn to have a better sense of humor and laugh more at myself and my mistakes.

### Sports
As a goal I want to do at least 5 minutes of exercise a day, Monday to Friday, throughout the year. I've discovered that it's easier for me to meet the exercise goal at night, and that I can take advantage of the 7 minutes of waiting for the french press to do push-ups. I think that in addition to that, I need to go running if I want to be able to finish a marathon.

### Technology
I want to keep participating in the Open Source space. I think here I don't need to impose much discipline on myself, these are things that naturally emerge:
* Increase my presence on twitter. Goal: 1000 followers.
* Create new apps in Streamlit: complete the Machine Learning and Confusion Matrix saga, and make the datasaurus.
* Participate in a free software development community, which could be the RISE one.
* Attend the Latin American PyCons, particularly the ones Ariel is organizing in Salta. Maybe some other international one.

### Reading
I have the goal of reading 10 non-fiction books and another 10 non-fiction books in the year 2022. For this I will set the goal of dedicating a little time every day and reading 1 fiction book and another non-fiction book per month. There are 2 months of tolerance for unfortunate events.

For the fiction books, I selected the ones Derek Sivers has marked 10/10: https://sive.rs/book

Topic: The world
1.- Open Borders - por Bryan Caplan

Topic: Writing
2.- On Writing Well - por William Zinsser

Topic: the mind
3.- Mindwise: How We Understand What Others Think, Believe, Feel, and Want - por Nicholas Epley
4.- The Time Paradox - por Philip Zimbardo y John Boyd

Topic: Learning
5.- The Listening Book - por W.A. Mathieu
6.- How Buildings Learn - por Stewart Brand
7.- E-Myth Revisited - por Michael Gerber

Topic: Life and death
8.- Forty Tales from the Afterlives - por David Eagleman
9.- The War of Art - por Steven Pressfield
10.- A Guide to the Good Life: The Ancient Art of Stoic Joy - por William Irvine

Other books:
1. Non designer design book
1. Resonate
1. Creativity INC
1. Invent and Wanter, Jeff Bezos
1. Zero to one
1. So good they cant ignore you
1. Numbers dont lie
1. Think Again
1. Antifragile
1. Almanak of Naval Ravikant
1. Why We Sleep: Unlocking the Power of Sleep and Dreams
1. The Sovereign Individual

Among the fiction books I would like to read or reread are:
1. Siddhartha, by Herman Hesse.
:::
