---
title: "Cocodrilito aprender a ir al baño"
title-en: "Little Crocodile learns to use the potty"
date: "2019-01-01"
description: "Un cuento escrito a 2 manos con mi hijo"
description-en: "A story written four-handed with my son"
categories: [escritura, cuento]
categories-en: [writing, story]
---

::: {.content-visible when-profile="esp"}
En una pequeña casita, en medio del África, vivían Papá Cocodrilo y Cocodilito. Papá Cocodrilo ya no se acordaba si Cocodrilito tenía 2 ó 3 años, pero sí sabía que ya era hora que fuera sólo al baño. Ya lo habían intentado antes, sin buenos resultados. Pero esta vez si les resultaría. Así que decidieron que Cocodrilito no usaría más pañales. Papá Cocodrilo no quería dejar solito a Cocodrilito en su primer día sin pañales, pero tenía que ir a cazar el almuerzo del día. No tuvo más remedio que decirle: Cocodrilito, si te dan ganas de hacer caca, grita muy fuerte, para que yo te escuche desde lejos. Y Cocodrilito preguntó: ¿Y qué tengo que gritar, papito? Y Papá cocodrilo le dijo: ¡Tienes que gritar, los más fuerte que puedas, caca, papá, caca! Así yo podré venir a ayudarte. Y entonces Papá Cocodrilo, se fue de la casa a cazar.

Cocodrilo llevaba esperando una hora, inmóvil y escondido en el lago. Esperaba que se acercara una cebra sedienta a tomar un sorbo de la refrescante agua. Y estaba a punto de atacarla cuando escucho a Cocodrilito gritar:
¡¡¡CACA, papá, CACA, papá, CACA!!!
Y papá Cocodrilo se apuró en llegar a casa. No atacó a la cebra. No tenía tiempo. Y venía tan apurado, que no se dio cuenta de las raíces del árbol y se tropezó. CRASH PUM OUCH AAAAAY!!! A Papá Cocodrilo se le cayeron 2 dientes. Pero se levantó, y siguió corriendo, hasta que llegó cerca a su casa, con una gran sonrisa de cocodrilo pensando que Cocodrilito había aprendido muy rápido y solito ir al baño.
Y Cocodrilito le repitió: ¡CACA, papá, CACA, papá, CACA!  CACA...HUATES.¡Se me cayeron los cacahuates que estaba comiendo!
¿Quéeeeeeeeee? - preguntó Papá Cocodrilo.
Mira papá, se me cayeron al suelo los cacahuates que estaba comiendo- le dijo cocodrilito.
Pero, pero, pero - dijo Papá Cocodrilo - yo estaba a punto a punto de atrapar una cebra, y pensé que me llamabas para ir al baño.
Nooo, papá, sólo te quería contar de los caca.. huates.
Bueno, dijo papá, me voy a seguir cazando nuestro almuerzo. Llámame solo cuando sea necesario ¿bueno? Y se fue nuevamente a cazar.

Cocodrilo ya no quiso cazar en el lago. Muy peligroso, se dijo a sí mismo, y se fue a cazar al tranquilo río que estaba más cerca de la casa. Se escondió entre los matorrales y espero que se acercara una nueva presa. Pasaron los minutos, y los minutos, y muchos minutos más… hasta que por fin, llegó una  jirafa. ¡Qué suerte que tengo! - dijo Papá Cocodrilo. Esta presa está mejor que la cebra. Y estaba a punto de saltar sobre el largo cuello de la jirafa cuando escucho a Cocodrilito:  ¡¡¡CACA, papá, CACA, papá, CACA!!!
Esta vez sí, se dijo Papá Cocodrilo, y nuevamente se apuró en llegar a casa. Venía tan apurado y preocupado, que no se dió cuenta que un puercoespín se había atravesado en su camino. Y por si no fuera poca su mala suerte, no sólo pisó el puercoespín y sus espinas que se le enterraron en los pies, sino que perdió el equilibrio y cayó sobre un cactus. CRASH PUM OUCH AAAAAY!!! Papá Cocodrilo se levantó de un brinco, se sacó cincuenta espinas de los pies, las manos y su hocico, y corrió rápidamente hasta llegar a su casa.

¡¡¡CACA, papá, CACA, papá, CACA!!!
¡Una caca-túa se comió los caca-huates que se me habían caído al piso!
Pero, pero, pero - dijo Papá Cocodrilo - ¡yo estaba a punto de atrapar una jirafa para comer! Pensé que esta vez sí que me llamabas para ir al baño.
Nooo, papá, sólo te quería contar de la caca.. túa que se comió los caca.. huates.
Bueno, dijo Papá Cocodrilo, seguiré cazando. Esta vez sí, llámame sólo cuando sea necesario, ¿vale?

Cocodrilo ya no quería cazar en el lago ni el río. Y se fue a cazar a la cascada. Sabía que había un elefante que siempre iba a tomar agua en la cascada. Papá Cocodrilo subió la ladera y esperó al elefante en la cima de la cascada. Esperó y esperó, esperó y esperó un rato, hasta que al fin, llegó el Elefante. Con su prima Elefanta y su papá Elefantón. Que suerte tengo -dijo Papá Cocodrilo- esto es incluso mejor que una cebra y una jirafa juntas. Cazar tres elefantes en un mismo día, tendremos un banquete. Y se acercaba sigilosamente, cuando de repente escuchó: ¡¡¡CACA, papá, CACA, papá, CACA!!! Y al escuchar a Cocodrilito se distrajo, y se resbaló, y cayó por la cascada.
CRASH PUM OUCH AAAAAY!!!
Con tan mala suerte, que cayó sobre papá Elefantón, que era famoso por su mal genio y su fuerte patada.
PUM OUCH AAAAAY!!!!
Un fuerte patadón de Elefantón lo levantó por los aires y llegó directo a su casa. Papá Cocodrilo se levantó, sin 2 dientes, todavía con algunas espinas, todo rasguñado y moreteado, y le preguntó a Cocodrilito: ¿Ahora sí, Cocodrilito? ¿Vamos al baño?
No papá, cáca-ras, papá, las caca-túa comió cacahuates y dejó cáca-ras en el piso.
¡¡¿¿QUEEEEE??!! -dijo el papá- estaba a punto de cazar 3 elefantes. Y además, no se dice cácara hijo, se dice, cáscara. Ahhh - dijo cocodrilito - cáscaras.

Papá - dijo cocodrilito - ahora sí necesito ir al baño.
¿A hacer caca? dijo papá.
Ay, papá, no seas vulgar, digámosle número dos.
:::

::: {.content-visible when-profile="eng"}
In a little house, in the middle of Africa, lived Papa Crocodile and Little Crocodile. Papa Crocodile could no longer remember whether Little Crocodile was 2 or 3 years old, but he did know it was high time he went to the potty on his own. They had tried before, without much luck. But this time it would work. So they decided that Little Crocodile would not wear diapers anymore. Papa Crocodile didn't want to leave Little Crocodile all alone on his first day without diapers, but he had to go hunt for the day's lunch. He had no choice but to tell him: Little Crocodile, if you feel like you have to poop, shout very loud, so that I can hear you from far away. And Little Crocodile asked: And what do I have to shout, daddy? And Papa Crocodile told him: You have to shout, as loud as you can, poop, papa, poop! That way I can come and help you. And then Papa Crocodile left the house to go hunting.

Crocodile had been waiting for an hour, motionless and hidden in the lake. He was waiting for a thirsty zebra to come and take a sip of the refreshing water. And he was just about to attack it when he heard Little Crocodile shout:
POOP, papa, POOP, papa, POOP!!!
And Papa Crocodile rushed home. He didn't attack the zebra. There was no time. And he came in such a hurry that he didn't notice the tree roots and tripped. CRASH BAM OUCH OWWW!!! Papa Crocodile lost 2 teeth. But he got up, and kept running, until he came near his house, with a big crocodile smile, thinking that Little Crocodile had learned to use the potty all by himself, and so quickly.
And Little Crocodile repeated: POOP, papa, POOP, papa, POOP! POO...NUTS. I dropped the peanuts I was eating! (In Spanish "caca" means poop and "cacahuates" means peanuts.)
Whaaaaaaaat? - asked Papa Crocodile.
Look, papa, I dropped the peanuts I was eating on the floor - said Little Crocodile.
But, but, but - said Papa Crocodile - I was just about, just about to catch a zebra, and I thought you were calling me to go to the potty.
Nooo, papa, I just wanted to tell you about the pea... nuts.
Well, said papa, I'm going back to hunt our lunch. Call me only when it's necessary, okay? And he went off hunting again.

Crocodile no longer wanted to hunt in the lake. Too dangerous, he told himself, and went to hunt in the calm river that was closer to the house. He hid among the bushes and waited for new prey to come near. The minutes passed, and passed, and many more minutes… until at last, a giraffe arrived. How lucky I am! - said Papa Crocodile. This prey is even better than the zebra. And he was just about to leap onto the giraffe's long neck when he heard Little Crocodile: POOP, papa, POOP, papa, POOP!!!
This time for sure, said Papa Crocodile to himself, and again he rushed home. He came in such a hurry and so worried that he didn't notice a porcupine had crossed his path. And as if his bad luck weren't enough, he not only stepped on the porcupine and its quills, which dug into his feet, but he also lost his balance and fell onto a cactus. CRASH BAM OUCH OWWW!!! Papa Crocodile jumped up, pulled fifty quills out of his feet, his hands, and his snout, and ran quickly until he reached his house.

POOP, papa, POOP, papa, POOP!!!
A cock-a-too ate the pea-nuts that had fallen on the floor! ("cacatúa" is cockatoo in Spanish, keeping the "caca" wordplay.)
But, but, but - said Papa Crocodile - I was just about to catch a giraffe to eat! I thought this time you really were calling me to go to the potty.
Nooo, papa, I just wanted to tell you about the cock-a-too that ate the pea-nuts.
Well, said Papa Crocodile, I'll keep hunting. This time for sure, call me only when it's necessary, all right?

Crocodile no longer wanted to hunt in the lake or the river. So he went to hunt at the waterfall. He knew there was an elephant who always went to drink water at the waterfall. Papa Crocodile climbed the slope and waited for the elephant at the top of the waterfall. He waited and waited, waited and waited a while, until at last, the Elephant arrived. With his cousin She-Elephant and his papa Big Elephant. How lucky I am - said Papa Crocodile - this is even better than a zebra and a giraffe together. Three elephants caught in a single day, we'll have a feast. And he was creeping up stealthily, when suddenly he heard: POOP, papa, POOP, papa, POOP!!! And on hearing Little Crocodile he got distracted, and slipped, and fell down the waterfall.
CRASH BAM OUCH OWWW!!!
And with such bad luck that he fell on top of Big Elephant, who was famous for his bad temper and his powerful kick.
BAM OUCH OWWW!!!!
A mighty kick from Big Elephant sent him flying through the air and he landed right at his house. Papa Crocodile got up, missing 2 teeth, still with a few quills in him, all scratched and bruised, and asked Little Crocodile: Now, Little Crocodile? Shall we go to the potty?
No papa, peeee-ls, papa, the cock-a-too ate the peanuts and left pee-ls on the floor. ("cáscaras" means peels/shells; the boy mispronounces it as "cácaras", again playing on "caca".)
Whaaaaat?! -said papa- I was just about to catch 3 elephants. And besides, it's not "pee-ls", son, it's "peels". Ahhh - said Little Crocodile - peels.

Papa - said Little Crocodile - now I really do need to go to the potty.
To poop? said papa.
Oh papa, don't be vulgar, let's call it number two.
:::
