---
title: El crimen del librero
title-en: The Bookseller's Murder
description: Concurso "Un detective en el Persa BioBio"
description-en: '"Un detective en el Persa BioBio" contest'
date: "2023-06-01"
categories: [escritura, microcuentos]
categories-en: [writing, flash fiction]
---

::: {.content-visible when-profile="esp"}
Como todos los lunes, Daniel Donoso se dirigió al galpón 1 del persa Bío-Bío. Desde que se había jubilado de detective de la PDI, tras veinte años de servicios y con cincuenta y seis años de edad, las novelas policiales se habían vuelto su pasatiempo. Fantaseaba con ponerse a escribir y contar algunos de sus mejores casos. Cuando llegó, le extrañó ver coches policiales y cruzarse con antiguos colegas. A pesar de su experiencia lidiando con cadáveres casi a diario, es distinto cuando quien muere es alguien que conoces. Bajo una manta plástica azul, yacía Ricardo Concha, su librero de siempre, con siete puñaladas en el pecho. Sus antiguos colegas le comentaron el caso. No era habitual que hablaran con civiles, pero el ex-detective Donoso seguía siendo conocido en la PDI por su registro de casos resueltos y su certera intuición. Habían cometido el crimen en la noche, sin testigos. Ricardo siempre era el último en partir del galpón, pues solía quedarse ordenando libros y leyendo. La principal sospechosa era Yanira, una colombiana que vendía arepas. Yanira había conquistado al público del persa a punta de curvas caribeñas, simpatía y un buen surtido de salsas picantes. Ricardo y Yanira llevaban un tiempo viviendo juntos y se les había visto pelear el domingo por la noche. Pero algo en su instinto de detective le hacía sospechar. El sitio del suceso no estaba desordenado y le parecía una muerte más premeditada que producto de una pelea doméstica. Un asesinato no le cuadraba con la imagen apasionada pero despreocupada de Yanira, a quién le sobraban pretendientes como para preocuparse por líos amorosos. Se preguntó quién ganaría con la muerte de Ricardo. ¿Otros libreros? No, claramente no elegían el oficio movidos por dinero sino por vocación. Los veía intercambiar libros y recomendaciones, sin competir por la clientela. Por hambre y costumbre, Daniel caminó hacia el puesto de Yanira. En su lugar, encontró el carro de sopaipillas de la señora Juanita, que volvía a estar lleno de sus antiguos clientes.
:::

::: {.content-visible when-profile="eng"}
As he did every Monday, Daniel Donoso headed to shed 1 of the Bío-Bío flea market. Ever since he had retired as a detective of the PDI, after twenty years of service and at fifty-six years of age, crime novels had become his pastime. He fantasized about taking up writing and recounting some of his best cases. When he arrived, he was surprised to see police cars and to run into former colleagues. Despite his experience dealing with corpses almost daily, it's different when the one who dies is someone you know. Beneath a blue plastic tarp lay Ricardo Concha, his longtime bookseller, with seven stab wounds in the chest. His former colleagues filled him in on the case. It wasn't usual for them to talk with civilians, but the former detective Donoso was still known at the PDI for his record of solved cases and his unerring intuition. The crime had been committed at night, with no witnesses. Ricardo was always the last to leave the shed, since he tended to stay behind arranging books and reading. The prime suspect was Yanira, a Colombian woman who sold arepas. Yanira had won over the flea market's crowd by means of Caribbean curves, charm and a good assortment of hot sauces. Ricardo and Yanira had been living together for some time and had been seen arguing on Sunday night. But something in his detective's instinct made him suspicious. The crime scene wasn't in disarray and it struck him as a more premeditated death than the result of a domestic fight. A murder didn't square with the passionate but carefree image of Yanira, who had more suitors than she'd ever need to worry over romantic troubles. He wondered who would gain from Ricardo's death. Other booksellers? No, clearly they hadn't chosen the trade driven by money but by vocation. He'd watched them exchange books and recommendations, without competing for the clientele. Out of hunger and habit, Daniel walked toward Yanira's stall. In its place, he found Mrs. Juanita's sopaipilla cart, which was once again full of her old customers.
:::
